pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Gradle Build') {
            steps {
                dir('java-gradle-app') {
                    bat 'gradlew.bat clean build'
                }
            }
        }

        stage('JUnit Tests') {
            steps {
                dir('java-gradle-app') {
                    bat 'gradlew.bat test'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('java-gradle-app') {
                    bat 'docker build -t java-gradle-app .'
                }
            }
        }

    }

    post {

        success {
            echo 'Pipeline executed successfully!'
        }

        failure {
            echo 'Pipeline failed!'
        }

    }

}