pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Gradle Build') {
            steps {
                bat 'gradlew.bat clean build'
            }
        }

        stage('JUnit Tests') {
            steps {
                bat 'gradlew.bat test'
            }
        }

        stage('Build Docker Image') {
            steps {
                bat 'docker build -t java-gradle-app .'
            }
        }

    }

    post {

        success {
            echo 'Pipeline executed successfully!'
        }

        failure {
            echo 'Pipeline failed!'
        }

    }

}